### PR TITLE
Fix margin in .row to be a correct calculation.

### PR DESCRIPTION
**Pull request by PeterBrun**
The 5.0.2 version generates the following CSS for .row:
`margin: -1rem -1.5rem;`

But it should have been (according to the code prior to a [refactor](https://github.com/vivid-web/flexboxgrid-sass/commit/6acc05edec230842cbb45f0e1301fc472c82d3d5)):
`margin: -1rem -0.5rem 1rem;`

This PR solves that problem.

### CODE REVIEW

**Comment by petervmeijgaard** [comment]
Hi @PeterBrun!

I just tested your PR and it works. Before merging this PR, could you run `yarn build` or `npm run build` to compile the SCSS?

Thanks for improving the quality of this project!

**Comment by PeterBrun** [comment]
Thanks. PR updated.

**Comment by petervmeijgaard** [comment]
Great! Thanks again! :+1:

**Comment by petervmeijgaard** [comment]
Fixed in V5.0.3

**Pull request merged**
